### ISSUE TITLE
Create travis build + deploy to dev instance

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-csw-ingester#1]

**Comment by allixender** [comment]
https://github.com/ZGIS/smart-csw-ingester/commit/2f11c6a3260ef06cb8207766844855108137bd67

**Comment by allixender** [comment]
Travis Build is done. The deploy to dev instance requirement is a whole other can of worms.

Can't immediately push to GKE Registry from Travis?

https://circleci.com/docs/continuous-deployment-with-google-container-engine/

http://scottsmerchek.com/2015/07/24/pushing-to-google-container-registry-from-circleci/

https://chengl.com/docker-workflow/

**Comment by allixender** [comment]
admin app receives webhook and issues gke container builder with the prepared source package from the the travis build. the deployment is currently requiring manual activation (click in the web gui) through the admin app, but could also be automated . the process is now complete pipeline from github to travis to gce/gke
