### ISSUE TITLE
BBOX parser does not parse (180,-180,-47,-34) correctly

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-csw-ingester#13]
Example Dataset is "0326a6b1-c163-405b-a3c7-9136ab4f4807".

```
               <gmd:extent>
                    <gmd:EX_Extent>
                        <gmd:geographicElement>
                            <gmd:EX_GeographicBoundingBox>
                                <gmd:westBoundLongitude>
                                    <gco:Decimal>-180</gco:Decimal>
                                </gmd:westBoundLongitude>
                                <gmd:eastBoundLongitude>
                                    <gco:Decimal>180</gco:Decimal>
                                </gmd:eastBoundLongitude>
                                <gmd:southBoundLatitude>
                                    <gco:Decimal>-47.175142</gco:Decimal>
                                </gmd:southBoundLatitude>
                                <gmd:northBoundLatitude>
                                    <gco:Decimal>-34.120108</gco:Decimal>
                                </gmd:northBoundLatitude>
                            </gmd:EX_GeographicBoundingBox>
                        </gmd:geographicElement>
                    </gmd:EX_Extent>
                </gmd:extent>
```

Result: `"bbox":[-180,-180,-34.120108,-47.175142]`

**Comment by allixender** [comment]
Sehr geil :weary: the westbound value holds the typical eastern most minimum longitude coordinate, and the eastbound value holds the western most maximum longitude value. How should we interpret this? Do they mean the whole world complete dateline wrap or a zero-width longitude window?

this:    (180,-180,-47,-34), and we do bboxFromCoords(east, west, south, north) -> Rect(minX=-180.0,maxX=-180.0,minY=-90.0,maxY=90.0)

Confirmed :ghost:

**Comment by allixender** [comment]
spatial4j builds rectangleand normalises from it: Rect(minX=-180.0,maxX=-180.0,minY=-90.0,maxY=90.0)

``` java
/** If true then {@link #normX(double)} will wrap longitudes outside of the standard
   * geodetic boundary into it. Example: 181 will become -179. */
  boolean isNormWrapLongitude();

/** Normalize the 'x' dimension. Might reduce precision or wrap it to be within the bounds. This
   * is called by {@link org.locationtech.spatial4j.io.ShapeReader}s before creating a shape. */
  double normX(double x);

```

I mean it really seems that it was entered just wrong way around into the metadata record, but logically it is zero width :laughing:

**Comment by grmpfhmbl** [comment]
Let's postpone the decision for now on how to handle these type of bounding boxes. It's not a bug but weird data :-)

**Comment by allixender** [comment]
I think I fucked something up, anyway. While (180,-180,-47,-34) is reverse/zero width longitudinal window, the shown metadata bounding box record seems actually valid from west -180 to east 180. This behaviour is now corrected in MdMetadataSet. The Zero width case should be discussed still, but can be postponed.

**Comment by allixender** [comment]
@grmpfhmbl Can be closed?!

**Comment by grmpfhmbl** [comment]
This should be handled more or less correctly now. :-)
