### ISSUE TITLE
Add additional SMART Category field to Lucene Doc

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-csw-ingester#18]
Add additional SMART Category field to Lucene Doc to be able to filter, boost, and feature SMART Groundwater Categories search

**Comment by allixender** [comment]
default functionality "just" looks into keywords, portal metadata adds categories to standard keyword list for now, ingester finds keywords anyway, frontend category cards based on simple keyword query for category names

**Comment by grmpfhmbl** [comment]
*hmpf* should have autoclosed
