### ISSUE TITLE
CSW Ingester provides proper OwcOfferings for advanced Linkages

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-csw-ingester#29]
CSW Ingester provides proper OwcOffering JSON to webgui,

so that at parsing and indexing time of MD_Metadata we know the most detail about the provided linkages and form relevant OwcOfferings with respective OwcOperations (depending on the MD_Metadata)

To be decided if this will be part of the MdMetadataSet GEoJSON or separate call/responseFormat (content type accept negotiation)

required by: https://github.com/ZGIS/smart-portal-webgui/issues/51

**Comment by grmpfhmbl** [comment]
Ok, CI_OnlineResouce is parsed completely now and can be stored in the index. Some magic is already in there, but now we need to create real OwcOfferings from that...
