### ISSUE TITLE
Unit-Tests for Lucene-Parser for parsing CSW content 

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-csw-ingester#4]
We have basic Lucene Unit test and basic CSW Scala XML parser test:
- https://github.com/ZGIS/smart-csw-ingester/blob/master/test/LuceneSpec.scala
- https://github.com/ZGIS/smart-csw-ingester/blob/master/test/ParserSpec.scala

We need to decide, which fields to start with:
- [x] file identifier / uuid
- [x] latest datestamp
- [x] keywords
- [x] title
- [x] abstract
- [x] contact names and organisation
- [x] license
- [x] BBOX (geometry accessible as wkt, bbox index and query)
- [x] source / origon catalog url

Based on test resources xml files test parsing those fields from MD_Metadata / GetRecordsResponse / GetRecordeByIdResponse into  Lucene docs / fields

**Comment by allixender** [comment]
date handling will need to be improved based on actual values that will occur "in the wild"

**Comment by allixender** [comment]
contact names, organisation, email, licenses handling are currently only string concatenations

**Comment by allixender** [comment]
Final edits neceesary around getting lucene-spatial-extras with BBoxStrategy to work:
http://lucene.apache.org/core/6_1_0/spatial-extras/org/apache/lucene/spatial/bbox/BBoxStrategy.html

**Comment by allixender** [comment]
We could discuss if keywords (essentially all "many item" lists) as indexed as concatened string or for each add doc field?

Time to test drive it on real catalogues...

**Comment by grmpfhmbl** [comment]
Ok, CSW parsing works for now. But you have to make sure, whatever XML you're parsing for actually exists. That was one of the errors in there. One document hadn't had a BBOX so in the end it boiled down to an Exception while creating the case class.

**Comment by allixender** [comment]
Yes, error handling would be good :smile:

**Comment by allixender** [comment]
discussed and reviewed in Trello
